// GENERATED by scripts/gen-asset-manifests.js — do not edit by hand.
/* eslint-disable */

export const artFiles: Partial<Record<string, number>> = {
  "brass_plate": require('./brass_plate.png'),
  "calendar": require('./calendar.png'),
  "candle": require('./candle.png'),
  "coin": require('./coin.png'),
  "coin_silver": require('./coin_silver.png'),
  "desk": require('./desk.png'),
  "envelope": require('./envelope.png'),
  "envelope_package": require('./envelope_package.png'),
  "item_corap": require('./item_corap.png'),
  "item_dut": require('./item_dut.png'),
  "lamp": require('./lamp.png'),
  "ledger": require('./ledger.png'),
  "magnifier": require('./magnifier.png'),
  "paper": require('./paper.png'),
  "pen": require('./pen.png'),
  "purse_note": require('./purse_note.png'),
  "stamp": require('./stamp.png'),
  "tray": require('./tray.png'),
  "window": require('./window.png'),
};
